server:
  port: 8761

eureka:
  instance:
    # eureka实例名称
    hostname: localhost
    # 显示IP
    prefer-ip-address: true
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 是否检索服务
    fetch-registry: false
    # Eureka注册服务的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  profiles:
    active: peer2


