server:
  port: 8762

spring:
  application:
    # 服务名
    name: service-hi
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      cors:
        allowed-origins: "*"
        allowed-methods: "*"