server:
  port: 9666
spring:
  profiles:
    active: elapse_route

---
spring:
  cloud:
    gateway:
      routes:
        # 每个router都需要一个唯一的id
        - id: after_route
          # 网关路由到http://httpbin.org:80/get
          uri: http://httpbin.org:80/get
          predicates:
            - After=2019-01-01T00:00:00.789-07:00[America/Denver]
  profiles: after_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://httpbin.org:80/get
          predicates:
            # 指定头名为X-Request-Id，且值为数字才会转发
            - Header=X-Request-Id, \d+
  profiles: header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: http://httpbin.org:80/get
          predicates:
            # 指定cookie名为name, cookie值为gsy才会转发
            - Cookie=name, gsy
  profiles: cookie_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
            # 指定头名为Host
            - Host=**.gsy.com
  profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org:80/get
          predicates:
            # GET类型的请求都转发到此路由
            - Method=GET
  profiles: method_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80/get
          predicates:
            # 指定请求路径
            - Path=/foo/{segment}
  profiles: path_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: http://httpbin.org:80/get
          predicates:
            # 指定请求中含有参数名为name，值的为gsy
            - Query=name, gsy
  profiles: query_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://httpbin.org:80/get
          filters:
            # AddRequestHeader过滤器工厂,加请求头
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - After=2019-01-01T00:00:00.789-07:00[America/Denver]
  profiles: add_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: rewritepath_route
          uri: https://blog.csdn.net
          predicates:
            - Path=/foo/**
          filters:
            # RewritePath过滤器工厂,重写/foo/路径,转发到https://blog.csdn.net
            - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: elapse_route
          uri: http://httpbin.org:80/get
          filters:
            - RequestTime=true
          predicates:
            - After=2019-01-01T00:00:00.789-07:00[America/Denver]
  profiles: elapse_route